env = Environment()
#env['CC'] = '../gfilt'
#env['CXX'] = '../gfilt'
#env['LINKERFORPROGRAMS'] = 'icpc'

if ARGUMENTS.get('debug', 0):
    env['CCFLAGS'] = '-Wall -Wextra -g -D_FILE_OFFSET_BITS=64 -std=c++0x'
elif ARGUMENTS.get('optimize', 0):
#    env['CCFLAGS'] = '-fast'
#    env['CCFLAGS'] = '-O9'
#    env['CCFLAGS'] = '-O2 -ftree-vectorize -ftree-vectorizer-verbose=3 -ffast-math -mtune=k8-sse3'
     env['CCFLAGS'] = '-O2 -ffast-math -mtune=k8-sse3'
elif ARGUMENTS.get('valgrind', 0):
    env['CCFLAGS'] = '-O0 -g'

env.Append( RPATH = '/usr/local/lib/');

env.Program(['Slingshot.cpp', 
         'JavaScript.cpp', 
         'HttpRequest.cpp', 
         'ResFile.cpp',
         'Indexer.cpp',
         'Resource.cpp',
         'SQLite.cpp',
         'Database.cpp',
         'JSDatabase.cpp',
         'Audio/Audio.cpp',
         'Audio/AudioEncoder.cpp',
         'Audio/AudioDecoder.cpp',
         'Audio/FLACDecoder.cpp', 
         'Audio/MP3Decoder.cpp',
         'Audio/VorbisEncoder.cpp', 
         'Audio/Metadata.cpp',
         'Image/Image.cpp', 
         'inotify-cxx/inotify-cxx.cpp',
], 
LIBS=['v8_g', 
      'microhttpd', 
      'sqlite3', 
      'boost_filesystem', 
      'boost_thread-mt',
      'FLAC++', 
      'vorbisenc', 
      'mpg123',
      'jpeg', 
      'png',
      'tag',
      'zbar',
#     'profiler',
#     'tcmalloc'
])

