env = Environment()
#env['CC'] = '../gfilt'
#env['CXX'] = '../gfilt'
#env['LINKERFORPROGRAMS'] = 'icpc'

env.ParseConfig('pkg-config --cflags --libs gstreamer-0.10')

if ARGUMENTS.get('debug', 0):
    env['CCFLAGS'] = '-Wall -Wextra -g -D_FILE_OFFSET_BITS=64 -std=c++0x'
elif ARGUMENTS.get('optimize', 0):
#    env['CCFLAGS'] = '-fast'
#    env['CCFLAGS'] = '-O9'
#    env['CCFLAGS'] = '-O2 -ftree-vectorize -ftree-vectorizer-verbose=3 -ffast-math -mtune=k8-sse3'
     env['CCFLAGS'] = '-O2 -ffast-math -mtune=k8-sse3 -D_FILE_OFFSET_BITS=64 -std=c++0x'
elif ARGUMENTS.get('valgrind', 0):
    env['CCFLAGS'] = '-O0 -g'

env.Append( RPATH = '/usr/local/lib/');

env.Program(['Slingshot.cpp', 
         'HttpRequest.cpp', 
         'ResFile.cpp',
         'Indexer.cpp',
         'Resource.cpp',
         'SQLite.cpp',
         'Database.cpp',
         'DBQuery.cpp',
         'Audio/Audio.cpp',
         'Audio/AudioEncoder.cpp',
         'Audio/AudioDecoder.cpp',
         'Audio/FLACDecoder.cpp', 
         'Audio/MP3Decoder.cpp',
         'Audio/VorbisEncoder.cpp', 
         'Audio/Metadata.cpp',
         'Image/Image.cpp', 
         'inotify-cxx/inotify-cxx.cpp',
         'video.cpp',
], 
LIBS=['microhttpd', 
      'sqlite3', 
      'boost_filesystem', 
      'boost_thread-mt',
      'boost_system',
      'FLAC++', 
      'FLAC',
      'ogg',
      'vorbis',
      'vorbisenc', 
      'mpg123',
      'jpeg', 
      'png',
      'tag',
      'zbar',
      'gstreamer-0.10',
      'gstapp-0.10',
      'gobject-2.0',
      'glib-2.0',
#     'profiler',
#     'tcmalloc'
])

